# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cata_related', to='Blog.Catagory', verbose_name='\u5206\u7c7b'),
        ),
    ]
